### ISSUE TITLE
Time out / out of memory with larger file

### ISSUE THREAD

**Issue by grv688** [mp3chapters/mp3chapters.github.io#21]
Hi. Is it possible to run a local instance that can handle larger mp3 files like audiobooks?  I have a 15 hour, 400+ MB book I'd like to add chapters to, but the browser eventually times out.  Thanks for this user friendly tool btw.

**Comment by DominikPeters** [comment]
Hi! Please try again (making sure to full refresh the page). I've updated it so that the wave image is only displayed for smaller files; this is usually the most compute intensive part and simultaneously useless for very long files.

**Comment by grv688** [comment]
Thank you!  The process now completes and I can save the file.  I don't see any additional tags or menus in the finished file and players that sometimes show chapter markers for mp3s (e.g., VLC) don't show them in this case, but I may be misunderstanding what the tool does.  In any event, thank you for the change!

**Comment by DominikPeters** [comment]
Few desktop apps currently have mp3 chapter support. The support is best for smartphone apps intended for podcasts, such as PocketCast (which can also play local files). If you've set any text fields (title, artist etc.) that should be shown correctly by all players.

**Comment by grv688** [comment]
Thanks - the chapters do show on pocketcasts!
