### ISSUE TITLE
Possibility to drop milliseconds/frames

### ISSUE THREAD

**Issue by dasrecht** [mp3chapters/mp3chapters.github.io#33]
Hi there

Love the mp3chapters tool - One thing that started to bug me is that Spotify seems not to take the milliseconds notation. So I started cutting those away manually. I think with a checkbox we could easily cut those automatically and thus simplify the process a bit. Or am I somehow on the wrong trail here?

/dasrecht

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added a checkbox to remove milliseconds from exported chapter times. Updated the exportAsPodlove, exportAsJSON, and exportAsList methods to respect this new option. Modified the secondsToString function to support removing milliseconds.

You can review changes in this commit: https://github.com/lkilu6456546/mp3chapters-mp3chapters.github.io-33/commit/bf9f80751d7fd57c22faab169956aa488532e135.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by DominikPeters** [comment]
Thanks for the idea. I decided that the easiest solution is to always strip out the milliseconds when using the "Copy chapter list" button. People who want to retain the milliseconds can easily select and Ctrl+C them from the edit field.

<img width="844" alt="image" src="https://github.com/user-attachments/assets/83da06ec-a662-4398-a104-3c0ee7b7600e">

**Comment by dasrecht** [comment]
Oh my - Way ahead of me 😂 Thanks for thinking about that already. 

Works as designed <3
