### ISSUE TITLE
No images and wrong duration in AntennaPod

### ISSUE THREAD

**Issue by arturi** [mp3chapters/mp3chapters.github.io#8]
Hi, thank you for your effort, this is an amazing tool. I'm on Linux and looking to add chapters with images to a podcast, there are very few options and the web version is exactly what I needed.

The problem I encountered is the images don't seem to get embedded, or they don't show up in AntennaPod on Android, plus the duration is wrong, so probably something incorrect about timestamps as well?

![photo_2024-01-10_09-40-13](https://github.com/mp3chapters/mp3chapters.github.io/assets/1199054/32166c9f-263a-4af3-b458-233f53685ac0)

Everything works fine with other mp3s from different podcasts in this app.

**Comment by DominikPeters** [comment]
Hi! Thanks for the report. I don't have an android device conveniently available, so cannot test on AntennaPod. Could you check what happens with PocketCasts? For me, on PocketCasts, it shows images.

Regarding chapter durations, maybe AntennaPod rounds down to 0? The example file has chapters that are only a few seconds long.

**Comment by DominikPeters** [comment]
I used an emulator, using another file with chapter images not produced with my tool, and AntennaPod also doesn't show chapter images. Maybe it's a bug of AntennaPod. Do you have an example podcast where a chapter image is shown?

**Comment by DominikPeters** [comment]
I think I figured it out. AntennaPod doesn't show chapter images when playing local files. If you add `https://mp3chapters.github.io/example.xml` as a podcast, the images are shown correctly.
<img width="302" alt="image" src="https://github.com/mp3chapters/mp3chapters.github.io/assets/3543224/f9bb7e2b-0a35-4e3e-add9-29922f8138dd">

**Comment by arturi** [comment]
Oooh I see. I was about to say I listened to [this podcast](https://mavecloud.s3mts.ru/storage/podcasts/14233b2d-a18b-4a88-b2a8-ed03e7abf9ef/episodes/b1ca7366-04eb-4841-a49f-7f563bd05a2f.mp3) yesterday where the images where shown correctly.

Thank you! Sorry for false alarm then, thank you for your work again :black_heart:
