### ISSUE TITLE
Any windows audio player that can read the corresponding JSON files

### ISSUE THREAD

**Issue by Hosseingsd** [mp3chapters/mp3chapters.github.io#9]
Apologies if this isn't the appropriate venue for my question, but I'm uncertain about where else to pose it.

I’m looking for a Windows application that can interpret JSON or XML data to display chapters as it plays my audio files. These files are personal, not podcasts, and I have no intention of uploading them. I’m comfortable with manually creating and editing JSON files for my audio tracks. All I need now is an audio player that can read the corresponding JSON files for each of my audio files and show the chapters.

**Comment by DominikPeters** [comment]
I agree it's weird that there are no desktop apps for playing MP3 files with chapters so I built one: https://mp3chapters.github.io/player/ It's very basic and I probably won't have time to improve it, but it works. It doesn't do JSON, only ID3 tags. Hope it's useful to you.
